### ISSUE TITLE
Complete README

### ISSUE THREAD

**Issue by MrGallo** [ICS3U-Gallo/cpt-linsi#1]
Please update your `README.md` file to include the title of your application and a description.

```
# Title
Description
```

**Comment by MrGallo** [comment]
This was not done. ?

**Comment by Linsi6280** [comment]
I just thought I have done that. I will add the title and description then.



Gmail 应用发送


2019年5月31日 星期五 -0400 14:34 发件人 notifications@github.com  <notifications@github.com>:

**Comment by MrGallo** [comment]
Thank you.
